graphql:
  servlet:
    mapping: /graphql
    cors-enabled: true
    exception-handlers-enabled: true

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    show-sql: true